---
title: "Estimates of the age/sex composition of the global refugee population at end-2022"
author: Sebastian Steinmueller (UNHCR)
format: pdf
bibliography: references.bib
execute:
  echo: false
  warning: false
  message: false
header-includes:
    \usepackage{float}
    \usepackage{setspace}
    \onehalfspacing
toc: true
lof: true
lot: true
---



```{r}
#| include: false
#| 
##### I. Read data, packages etc ##### 

### packages
library(tidyverse)
library(stringi)
library(gt)
library(ggplot2)
library(patchwork)
library(scales)
library(ggdist)
library(tidybayes)
library(brms)
library(equatiomatic)
library(writexl)

### read datasets
load("data/dem_refoip_end2022.RData")
imputations <- readRDS("output/imputations400_20230607.rds")

### read brms fit object
# m.ageonly <- readRDS("models/m.ageonly_20230509.rds")

## colours (https://intranet.unhcr.org/content/dam/unhcr/intranet/staff%20support/strategic/documents/english/brand-book/UNHCR-Brand%20Book.pdf)
unhcrPaletteBlue <- c("#0072BC", "#338EC9", "#66AAD7", "#99C7E4", "#CCE3F2")
unhcrPaletteBlack <- c("#000000", "#333333", "#666666", "#999999", "#CCCCCC")
unhcrPaletteYellow <- c("#FAEB00", "#FBEF33", "#FCF366", "#FDF799", "#FEFBCC")
unhcrPaletteWhite <- c("#FFFFFF")
unhcrPaletteRed <- c("#E73451")
unhcrPaletteGreen <- c("#00AB92")


##### II. Plot hierarchies and covariates ##### 

# Calculate the proportions of children and girls/women
dem_longMissing <- dem_longMissing %>%
  mutate(childrenProp = children/total,
         femaleProp = female/total,
         missingAge = case_when(
              missing == "none" ~ "Age not missing",
              missing != "none" ~ "Age missing" 
            ),
         origin_countryShort = case_when(
              origin_country == "Venezuela (Bolivarian Republic of)" ~ "Venezuela" ,
              origin_country == "United Kingdom of Great Britain and Northern Ireland" ~ "UK",
              origin_country == "Bolivia (Plurinational State of)" ~ "Bolivia",
              origin_country == "Central African Republic" ~ "CAR",
              origin_country == "China, Hong Kong Special Administrative Region" ~ "Hong Kong",
              origin_country == "Lao People's Democratic Republic" ~ "Lao",
              origin_country == "Russian Federation" ~ "Russia",
              origin_country == "Syrian Arab Republic" ~ "Syria",
              origin_country == "Democratic Republic of the Congo" ~ "DRC",
              origin_country == "United Republic of Tanzania" ~ "Tanzania",
              origin_country == "United States of America" ~ "USA",
              origin_country == "United Arab Emirates" ~ "UAE",
              TRUE ~ as.character(origin_country)
          ),
         asylum_countryShort = case_when(
              asylum_country == "Venezuela (Bolivarian Republic of)" ~ "Venezuela" ,
              asylum_country == "United Kingdom of Great Britain and Northern Ireland" ~ "UK",
              asylum_country == "Bolivia (Plurinational State of)" ~ "Bolivia",
              asylum_country == "Central African Republic" ~ "CAR",
              asylum_country == "China, Hong Kong Special Administrative Region" ~ "Hong Kong",
              asylum_country == "Lao People's Democratic Republic" ~ "Lao",
              asylum_country == "Russian Federation" ~ "Russia",
              asylum_country == "Syrian Arab Republic" ~ "Syria",
              asylum_country == "Democratic Republic of the Congo" ~ "DRC",
              asylum_country == "United Republic of Tanzania" ~ "Tanzania",
              asylum_country == "United States of America" ~ "USA",
              asylum_country == "United Arab Emirates" ~ "UAE",
              TRUE ~ as.character(asylum_country)  
          )
         ) %>% 
  mutate(origin_countryShort = factor(origin_countryShort), 
         asylum_countryShort = factor(asylum_countryShort))

imputations <- imputations %>% 
   mutate(childrenProp = children/total,
          femaleProp = female/total,
          origin_countryShort = case_when(
              origin_country == "Venezuela (Bolivarian Republic of)" ~ "Venezuela" ,
              origin_country == "United Kingdom of Great Britain and Northern Ireland" ~ "UK",
              origin_country == "Bolivia (Plurinational State of)" ~ "Bolivia",
              origin_country == "Central African Republic" ~ "CAR",
              origin_country == "China, Hong Kong Special Administrative Region" ~ "Hong Kong",
              origin_country == "Lao People's Democratic Republic" ~ "Lao",
              origin_country == "Russian Federation" ~ "Russia",
              origin_country == "Syrian Arab Republic" ~ "Syria",
              origin_country == "Democratic Republic of the Congo" ~ "DRC",
              origin_country == "United Republic of Tanzania" ~ "Tanzania",
              origin_country == "United States of America" ~ "USA",
              origin_country == "United Arab Emirates" ~ "UAE",
              TRUE ~ as.character(origin_country)
          ),
         asylum_countryShort = case_when(
              asylum_country == "Venezuela (Bolivarian Republic of)" ~ "Venezuela" ,
              asylum_country == "United Kingdom of Great Britain and Northern Ireland" ~ "UK",
              asylum_country == "Bolivia (Plurinational State of)" ~ "Bolivia",
              asylum_country == "Central African Republic" ~ "CAR",
              asylum_country == "China, Hong Kong Special Administrative Region" ~ "Hong Kong",
              asylum_country == "Lao People's Democratic Republic" ~ "Lao",
              asylum_country == "Russian Federation" ~ "Russia",
              asylum_country == "Syrian Arab Republic" ~ "Syria",
              asylum_country == "Democratic Republic of the Congo" ~ "DRC",
              asylum_country == "United Republic of Tanzania" ~ "Tanzania",
              asylum_country == "United States of America" ~ "USA",
              asylum_country == "United Arab Emirates" ~ "UAE",
              TRUE ~ as.character(asylum_country)  
          )
         ) %>% 
  mutate(origin_countryShort = factor(origin_countryShort), 
         asylum_countryShort = factor(asylum_countryShort))

```


# Results

## Global and regional estimates

```{r, message=FALSE, warning=FALSE}
#| warning: false
#| error: false
#| echo: false
#| message: false


### Global

imputations.world <- imputations |>
  group_by(year, imputation) |> 
  summarise(across(female_0_4:total, sum)) %>%
  mutate(childrenProp = children/total,
         femaleProp = female/total,
         elderlyProp = elderly/total)


t.imp.world <- imputations.world |>
  group_by(year) %>%
  summarise(across(c(total, childrenProp, femaleProp, elderlyProp, female, male, children, girls, boys, adults, elderly, female_0_4:female_60, male_0_4:male_60), 
                   list(mean = mean, 
                        lower95UI = ~quantile(.x,probs = 0.025),
                        upper95UI = ~quantile(.x,probs = 0.975)
                        )
                   )
            ) %>%
  select(-total_lower95UI, -total_upper95UI) %>%
  rename(total = total_mean)


### Region of asylum

imputations.asy.region <- imputations |>
  group_by(year, asylum_region, imputation) |> 
  summarise(across(female_0_4:total, sum)) %>%
  ungroup() %>%
  mutate(childrenProp = children/total,
         femaleProp = female/total,
         elderlyProp = elderly/total)


t.imp.asy.region <- imputations.asy.region |>
  group_by(year, asylum_region) %>%
  summarise(across(c(total, childrenProp, femaleProp, elderlyProp, female, male, children, girls, boys, adults, elderly, female_0_4:female_60, male_0_4:male_60), 
                   list(mean = mean, 
                        lower95UI = ~quantile(.x,probs = 0.025),
                        upper95UI = ~quantile(.x,probs = 0.975)
                        )
                   )
            ) %>%
  select(-total_lower95UI, -total_upper95UI) %>%
  rename(total = total_mean)


### UNHCR region of asylum

imputations.asy.unhcrregion <- imputations |>
  group_by(year, asylum_hcr_region, imputation) |> 
  summarise(across(female_0_4:total, sum)) %>%
  ungroup() %>%
  mutate(childrenProp = children/total,
         femaleProp = female/total,
         elderlyProp = elderly/total)


t.imp.asy.unhcrregion <- imputations.asy.unhcrregion |>
  group_by(year, asylum_hcr_region) %>%
  summarise(across(c(total, childrenProp, femaleProp, elderlyProp, female, male, children, girls, boys, adults, elderly, female_0_4:female_60, male_0_4:male_60), 
                   list(mean = mean, 
                        lower95UI = ~quantile(.x,probs = 0.025),
                        upper95UI = ~quantile(.x,probs = 0.975)
                        )
                   )
            ) %>%
  select(-total_lower95UI, -total_upper95UI) %>%
  rename(total = total_mean)


### Country of asylum

imputations.asy <- imputations |>
  group_by(year, asylum_iso3, asylum_country, imputation) |> 
  summarise(across(female_0_4:total, sum)) %>%
  ungroup() %>%
  mutate(childrenProp = children/total,
         femaleProp = female/total,
         elderlyProp = elderly/total)


t.imp.asy <- imputations.asy |>
  group_by(year, asylum_iso3, asylum_country) %>%
  summarise(across(c(total, childrenProp, femaleProp, elderlyProp, female, male, children, girls, boys, adults, elderly, female_0_4:female_60, male_0_4:male_60), 
                   list(mean = mean, 
                        lower95UI = ~quantile(.x,probs = 0.025),
                        upper95UI = ~quantile(.x,probs = 0.975)
                        )
                   )
            ) %>%
  select(-total_lower95UI, -total_upper95UI) %>%
  rename(total = total_mean)



### Country of origin

imputations.ori <- imputations |>
  group_by(year, origin_iso3, origin_country, imputation) |> 
  summarise(across(female_0_4:total, sum)) %>%
  ungroup() %>%
  mutate(childrenProp = children/total,
         femaleProp = female/total,
         elderlyProp = elderly/total)


t.imp.ori <- imputations.ori |>
  group_by(year, origin_iso3, origin_country,) %>%
  summarise(across(c(total, childrenProp, femaleProp, elderlyProp, female, male, children, girls, boys, adults, elderly, female_0_4:female_60, male_0_4:male_60), 
                   list(mean = mean, 
                        lower95UI = ~quantile(.x,probs = 0.025),
                        upper95UI = ~quantile(.x,probs = 0.975)
                        )
                   )
            ) %>%
  select(-total_lower95UI, -total_upper95UI) %>%
  rename(total = total_mean)




### Country of asylum, origin, population type

imputations.countries <- imputations |>
  ungroup() %>%
  mutate(childrenProp = children/total,
         femaleProp = female/total,
         elderlyProp = elderly/total)


t.imp.countries <- imputations.countries |>
  group_by(year, asylum_iso3, asylum_country, origin_iso3, origin_country, popType) %>%
  summarise(across(c(total, childrenProp, femaleProp, elderlyProp, female, male, children, girls, boys, adults, elderly, female_0_4:female_60, male_0_4:male_60), 
                   list(mean = mean, 
                        lower95UI = ~quantile(.x,probs = 0.025),
                        upper95UI = ~quantile(.x,probs = 0.975)
                        )
                   )
            ) %>%
  select(-total_lower95UI, -total_upper95UI) %>%
  rename(total = total_mean)

    
```


```{r, message=FALSE, warning=FALSE}
#| warning: false
#| error: false
#| echo: false
#| message: false


### write

write_xlsx(
  list(
    "World" = t.imp.world,
    "World region of asylum" = t.imp.asy.region,
    "UNHCR region of asylum" = t.imp.asy.unhcrregion,
    "Country of asylum" = t.imp.asy,
    "Country of origin" = t.imp.ori,
    "Country pairs" = t.imp.countries
  ),
  path  = paste0("output/Demographic estimates GT23_", str_remove_all(as.character(Sys.Date()), "-"),".xlsx")
)
  



```

